### ISSUE TITLE
withDirectoryMode do nothing, ignored

### ISSUE THREAD

**Issue by sartor** [yiisoft/cache-file#46]
### What steps will reproduce the problem?
->withDirectoryMode(0777)
->withDirectoryLevel(0);
### What is the expected result?
directory created with 0777
### What do you get instead?
directory created with default 0775

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.0
| PHP version      | 8.1
| Operating system | Linux Mint 20.3

Because of `createDirectoryIfNotExists()` in `FileCache` constructor building object with other than default directory mode will be ignored

**Comment by vjik** [comment]
Fixed by https://github.com/yiisoft/cache-file/pull/47

**Comment by vjik** [comment]
> withDirectoryMode

[Tests](https://github.com/yiisoft/cache-file/blob/f6bb2fea2403226530b314dc1fb139b73d305fa5/tests/FileCacheTest.php#L436) is pass. Can you give more details (OS, package version, example of code)?

**Comment by sartor** [comment]
This test only work if directoryLevel === 1. But if we change it to 0 (no sub directories) all subdirectories wiil be created with default permissions (0755) instead of 0777.

To reproduce simply add `->withDirectoryLevel(0)` to line `$newCache = $cache->withDirectoryMode(0777)` in `testDirMode()` test:
```php
    public function testDirMode(): void
    {
        if ($this->isWindows()) {
            $this->markTestSkipped('Can not test permissions on Windows');
        }

        $cache = new FileCache($this->tmpDir);
        $newCache = $cache->withDirectoryMode(0777)->withDirectoryLevel(0);

        $this->assertInstanceOf(FileCache::class, $newCache);
        $this->assertNotSame($cache, $newCache);

        $newCache->set('a', 1);
        $this->assertSameExceptObject(1, $newCache->get('a'));

        $cacheFile = $this->invokeMethod($newCache, 'getCacheFile', ['a']);
        $permissions = substr(sprintf('%o', fileperms(dirname($cacheFile))), -4);

        $this->assertEquals('0777', $permissions);
    }
```

Output (phpunit):
```
There was 1 failure:

1) Yiisoft\Cache\File\Tests\FileCacheTest::testDirMode
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'0777'
+'0775'

/home/sartor/projects/cache-file/tests/FileCacheTest.php:454
```
